create table severity_levels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  rank integer not null,
  color_hint text
);

-- Enable Row Level Security
alter table severity_levels enable row level security;

-- Policies
-- Allow SELECT for any authenticated user
create policy "Allow read access for authenticated users"
  on severity_levels
  for select
  using (auth.role() = 'authenticated');

-- Allow INSERT/UPDATE/DELETE only for admin role
create policy "Allow write access for admin only"
  on severity_levels
  for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );