create table disaster_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean default true
);

-- Enable Row Level Security
alter table disaster_types enable row level security;

-- Policies
-- Allow SELECT for any authenticated user
create policy "Allow read access for authenticated users"
  on disaster_types
  for select
  using (auth.role() = 'authenticated');

-- Allow INSERT/UPDATE/DELETE only for admin role
create policy "Allow write access for admin only"
  on disaster_types
  for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );