create table resource_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text,
  unit text,
  is_expiry_tracked boolean default false,
  default_minimum_stock integer default 0,
  is_active boolean default true
);

-- Enable Row Level Security
alter table resource_types enable row level security;

-- Policies
-- Allow SELECT for any authenticated user
create policy "Allow read access for authenticated users"
  on resource_types
  for select
  using (auth.role() = 'authenticated');

-- Allow INSERT/UPDATE/DELETE only for admin or inventory_manager role
create policy "Allow write access for admin/inventory_manager"
  on resource_types
  for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role in ('admin', 'inventory_manager')
    )
  );